name: vote_vault
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  blurrycontainer: ^2.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/otp.png
